document.transcriptionator = {};
document.transcriptionator.results = {
  "title": "rm_interviews_yy",
  "description": "transcription services by Transcriptionator 1000",
  "location": "unknown",
  "date": "2024-10-28 21:06:10",
  "speakers_segments": [
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0,
    1,
    0
  ],
  "speakers_all": [
    0,
    1
  ],
  "segments": [
    {
      "segment": 0,
      "start": 0.7565937500000001,
      "end": 21.00659375,
      "speaker": 0,
      "path_audio": "segments/00.mp3",
      "path_transcript": "segments/00_transcript.json",
      "transcript": " Yulia Navalnya is a Russian opposition leader. She is the wife now, the widow of Alexei Navalny. Navalny's secret prison diaries and his memoir are somehow miraculously being published this week. The book is called Patriot, a memoir. I read every word of the book. I could not put it down. Yulia Navalnya, it is a real honor to have you here. Thank you.",
      "language": "en",
      "emotions": [
        2,
        2,
        65,
        81,
        73,
        25,
        61
      ],
      "emotion": 3
    },
    {
      "segment": 1,
      "start": 21.31034375,
      "end": 27.38534375,
      "speaker": 1,
      "path_audio": "segments/01.mp3",
      "path_transcript": "segments/01_transcript.json",
      "transcript": " Hello Rachel, thank you for having me. It's a great honor and thank you for your kind words. It means a lot.",
      "language": "en",
      "emotions": [
        26,
        41,
        18,
        92,
        31,
        86,
        73
      ],
      "emotion": 3
    },
    {
      "segment": 2,
      "start": 27.38534375,
      "end": 32.549093750000004,
      "speaker": 0,
      "path_audio": "segments/02.mp3",
      "path_transcript": "segments/02_transcript.json",
      "transcript": " Did I say anything that revs you the wrong way or that seemed wrong to you? Oh, you know, you said...",
      "language": "en",
      "emotions": [
        19,
        60,
        1,
        89,
        49,
        4,
        40
      ],
      "emotion": 3
    },
    {
      "segment": 3,
      "start": 32.549093750000004,
      "end": 38.26971875,
      "speaker": 1,
      "path_audio": "segments/03.mp3",
      "path_transcript": "segments/03_transcript.json",
      "transcript": " too many good words in advance I guess some of them.",
      "language": "en",
      "emotions": [
        9,
        91,
        39,
        23,
        45,
        71,
        25
      ],
      "emotion": 1
    },
    {
      "segment": 4,
      "start": 38.26971875,
      "end": 38.32034375,
      "speaker": 0,
      "path_audio": "segments/04.mp3",
      "path_transcript": "segments/04_transcript.json",
      "transcript": "",
      "language": "ko",
      "emotions": [
        24,
        49,
        97,
        57,
        0,
        55,
        6
      ],
      "emotion": 2
    },
    {
      "segment": 5,
      "start": 38.32034375,
      "end": 38.38784375,
      "speaker": 1,
      "path_audio": "segments/05.mp3",
      "path_transcript": "segments/05_transcript.json",
      "transcript": "",
      "language": "en",
      "emotions": [
        25,
        41,
        46,
        29,
        36,
        81,
        77
      ],
      "emotion": 5
    },
    {
      "segment": 6,
      "start": 38.38784375,
      "end": 82.88721875,
      "speaker": 0,
      "path_audio": "segments/06.mp3",
      "path_transcript": "segments/06_transcript.json",
      "transcript": " Thank you. I will tell you, we're in the midst of a very heated election system season in this country, as you know. And my confession to you is that I did not intend to read all of the book. I thought, I am not going to have time. I'm really busy. I'm going to read the beginning. And the end, have other people read it and tell me what's about. I read every word of it. I couldn't stop reading it. I found it incredibly moving. Thank you. Can you tell me a little bit about what it took to get the book into print? I imagine that you had to have a hand in editing the manuscript. I imagine there may have been some hard decisions for you in terms of things that felt personal, that you might have want to keep between you and your husband that you never the less put in the book. What was it like to bring it to fruition?",
      "language": "en",
      "emotions": [
        78,
        18,
        29,
        43,
        35,
        37,
        30
      ],
      "emotion": 0
    },
    {
      "segment": 7,
      "start": 83.47784375,
      "end": 83.49471875,
      "speaker": 1,
      "path_audio": "segments/07.mp3",
      "path_transcript": "segments/07_transcript.json",
      "transcript": "",
      "language": "en",
      "emotions": [
        23,
        51,
        25,
        28,
        54,
        27,
        53
      ],
      "emotion": 4
    },
    {
      "segment": 8,
      "start": 83.49471875,
      "end": 83.89971875,
      "speaker": 0,
      "path_audio": "segments/08.mp3",
      "path_transcript": "segments/08_transcript.json",
      "transcript": " Resolute.",
      "language": "en",
      "emotions": [
        15,
        32,
        12,
        11,
        93,
        50,
        7
      ],
      "emotion": 4
    },
    {
      "segment": 9,
      "start": 83.89971875,
      "end": 119.92784375000001,
      "speaker": 1,
      "path_audio": "segments/09.mp3",
      "path_transcript": "segments/09_transcript.json",
      "transcript": " important for me this book is my memory of my husband his legacy and that's why it was difficult in some ways to put some parts together but I would say to you that we didn't cut a lot in editing. No, I think that everything in what was in this book it was true and I wanted to keep Alexis voice to sound loud and to sound open and",
      "language": "en",
      "emotions": [
        72,
        65,
        7,
        34,
        16,
        2,
        61
      ],
      "emotion": 0
    },
    {
      "segment": 10,
      "start": 106.73159375,
      "end": 119.01659375000001,
      "speaker": 0,
      "path_audio": "segments/10.mp3",
      "path_transcript": "segments/10_transcript.json",
      "transcript": " in editing. No, I think that everything in what was in this book, it was true, and I wanted to keep Alexis voice to sound loud and to sound open.",
      "language": "en",
      "emotions": [
        55,
        50,
        41,
        26,
        11,
        17,
        44
      ],
      "emotion": 0
    },
    {
      "segment": 11,
      "start": 121.76721875000001,
      "end": 125.78346875000001,
      "speaker": 1,
      "path_audio": "segments/11.mp3",
      "path_transcript": "segments/11_transcript.json",
      "transcript": " his voice to bring the truth.",
      "language": "en",
      "emotions": [
        71,
        99,
        18,
        87,
        19,
        39,
        90
      ],
      "emotion": 1
    },
    {
      "segment": 12,
      "start": 125.78346875000001,
      "end": 181.48784375000002,
      "speaker": 0,
      "path_audio": "segments/12.mp3",
      "path_transcript": "segments/12_transcript.json",
      "transcript": " When he writes in the book about sort of spontaneously saying to a crowd of people that has assembled when he's been arrested, he's in trouble with the law, and nobody knows what's going to happen to him. And he seems to sort of, he writes how he sort of surprised himself by saying, don't be afraid of anything. He writes about it as if that kind of burst out of him. And he was happy that it burst out of him. It's something that he'd been feeling, but he hadn't articulated that way. I think people in this country, certainly people around the world, indelibly think of him with that sentiment, not only because we know what ultimately happened to him, because long before they killed him, we knew what they were doing to him. And for him to not be afraid himself, but to tell other people, this is the secret. This is the way out of repression. This is the way to beat a dictator, is to not be afraid of him. Do you know where he learned that? I mean, it seems like you believe it, too. Did the two of you come up with it?",
      "language": "en",
      "emotions": [
        59,
        7,
        66,
        33,
        96,
        22,
        30
      ],
      "emotion": 4
    },
    {
      "segment": 13,
      "start": 181.85909375,
      "end": 189.30096875,
      "speaker": 1,
      "path_audio": "segments/13.mp3",
      "path_transcript": "segments/13_transcript.json",
      "transcript": " I believe in it, but of course I would like to know more of his secrets because he had...",
      "language": "en",
      "emotions": [
        98,
        70,
        40,
        44,
        8,
        74,
        96
      ],
      "emotion": 0
    },
    {
      "segment": 14,
      "start": 187.19159375,
      "end": 187.34346875,
      "speaker": 0,
      "path_audio": "segments/14.mp3",
      "path_transcript": "segments/14_transcript.json",
      "transcript": " are",
      "language": "en",
      "emotions": [
        34,
        66,
        18,
        38,
        22,
        22,
        35
      ],
      "emotion": 1
    },
    {
      "segment": 15,
      "start": 189.38534375,
      "end": 250.89471875,
      "speaker": 1,
      "path_audio": "segments/15.mp3",
      "path_transcript": "segments/15_transcript.json",
      "transcript": " The superpower is some ways, and he was so easily able to motivate people and to encourage people. Probably, the secret is just to be honest with people, to be close to people, to love people, to believe in what you're doing, and just to follow these directions and to follow your inner rules. And it's very important to do this then. To love country, to love family, to love the things you're doing, not to go to the office just to go to the office every day doing your job, just to live in this job, with this job, with this belief, a belief. And I think that it was for him not very hard because he believed in everything what he was doing.",
      "language": "en",
      "emotions": [
        69,
        57,
        90,
        46,
        2,
        55,
        51
      ],
      "emotion": 2
    },
    {
      "segment": 16,
      "start": 252.05909375000002,
      "end": 308.96159375,
      "speaker": 0,
      "path_audio": "segments/16.mp3",
      "path_transcript": "segments/16_transcript.json",
      "transcript": " One of the things he writes about that's very moving is how much your support meant to him and how much it made him more capable as a leader and as an activist to know that you were with him, that you agreed with him, that you already agreed with him before he'd ever had a chance to talk to you about it. He talks about it very movingly when he's been poisoned with a nerve agent. He's nearly three weeks in a coma in Germany. He's very nearly kill him. And he writes movingly about how your presence was a neurobiological miracle. It was the only thing that brought him back. And the thing that I thought about that, preparing to talk to you today, is that in many ways you've stepped into his shoes. You're the leader of the Russian opposition because he can't be anymore. But who can be that role for you? Who can support you the way that he supported him?",
      "language": "en",
      "emotions": [
        27,
        52,
        54,
        5,
        8,
        3,
        9
      ],
      "emotion": 2
    },
    {
      "segment": 17,
      "start": 310.22721875,
      "end": 310.24409375000005,
      "speaker": 1,
      "path_audio": "segments/17.mp3",
      "path_transcript": "segments/17_transcript.json",
      "transcript": "",
      "language": "en",
      "emotions": [
        20,
        49,
        34,
        41,
        26,
        20,
        43
      ],
      "emotion": 1
    },
    {
      "segment": 18,
      "start": 310.24409375000005,
      "end": 310.44659375000003,
      "speaker": 0,
      "path_audio": "segments/18.mp3",
      "path_transcript": "segments/18_transcript.json",
      "transcript": "",
      "language": "en",
      "emotions": [
        6,
        83,
        22,
        30,
        29,
        97,
        27
      ],
      "emotion": 5
    },
    {
      "segment": 19,
      "start": 310.44659375000003,
      "end": 310.78409375,
      "speaker": 1,
      "path_audio": "segments/19.mp3",
      "path_transcript": "segments/19_transcript.json",
      "transcript": "...",
      "language": "ko",
      "emotions": [
        28,
        2,
        5,
        86,
        91,
        84,
        32
      ],
      "emotion": 4
    },
    {
      "segment": 20,
      "start": 310.78409375,
      "end": 310.96971875,
      "speaker": 0,
      "path_audio": "segments/20.mp3",
      "path_transcript": "segments/20_transcript.json",
      "transcript": "",
      "language": "ko",
      "emotions": [
        28,
        40,
        92,
        34,
        10,
        38,
        32
      ],
      "emotion": 2
    },
    {
      "segment": 21,
      "start": 310.96971875,
      "end": 338.56034375,
      "speaker": 1,
      "path_audio": "segments/21.mp3",
      "path_transcript": "segments/21_transcript.json",
      "transcript": " Thank you everything what you are saying it's a compliment and it's very nice to hear it I think you call me the leader of opposition a little bit in advance I would call myself a young politician probably in some ways of course I knew about politics a lot because I've been living with the leader Real leader of opposition for many years But I promise I'll do my best",
      "language": "en",
      "emotions": [
        46,
        17,
        63,
        57,
        86,
        20,
        38
      ],
      "emotion": 4
    },
    {
      "segment": 22,
      "start": 338.99909375000004,
      "end": 339.23534375,
      "speaker": 0,
      "path_audio": "segments/22.mp3",
      "path_transcript": "segments/22_transcript.json",
      "transcript": "",
      "language": "en",
      "emotions": [
        88,
        24,
        52,
        91,
        93,
        18,
        19
      ],
      "emotion": 4
    },
    {
      "segment": 23,
      "start": 339.23534375,
      "end": 373.10346875000005,
      "speaker": 1,
      "path_audio": "segments/23.mp3",
      "path_transcript": "segments/23_transcript.json",
      "transcript": " And it's very important for me in many reasons, and for my country, and for my family, and for my children, and for Alexis Memory. Who support me? I think that it's the main problem, because of course we supported each other. Yeah. And it was very easy for him, and very easy for me in some very difficult moments, because after all these structures, we can go...",
      "language": "en",
      "emotions": [
        86,
        40,
        9,
        67,
        30,
        10,
        31
      ],
      "emotion": 0
    },
    {
      "segment": 24,
      "start": 357.30846875000003,
      "end": 357.52784375000005,
      "speaker": 0,
      "path_audio": "segments/24.mp3",
      "path_transcript": "segments/24_transcript.json",
      "transcript": " Yeah.",
      "language": "en",
      "emotions": [
        6,
        53,
        80,
        31,
        59,
        26,
        25
      ],
      "emotion": 2
    },
    {
      "segment": 25,
      "start": 373.42409375,
      "end": 433.95471875000004,
      "speaker": 1,
      "path_audio": "segments/25.mp3",
      "path_transcript": "segments/25_transcript.json",
      "transcript": " to lie down on the bed touching our hands. And it was like very helpful. And I miss it a lot. And I am doing all these interviews, meetings, and everything. And what I wish a lot to come back home every evening and to discuss everything with him, right? Even when he was imprisoned to write him a letter, telling what was going on in my life. But still, I think that love to him, love to country, all the supporters who supported Alexei and who support me now, they give me power. And I appreciate all these kind words, a lot of letters of support from many, many people.",
      "language": "en",
      "emotions": [
        11,
        12,
        48,
        75,
        11,
        18,
        25
      ],
      "emotion": 3
    },
    {
      "segment": 26,
      "start": 435.79409375,
      "end": 506.83784375000005,
      "speaker": 0,
      "path_audio": "segments/26.mp3",
      "path_transcript": "segments/26_transcript.json",
      "transcript": " Even since, Alex, it was killed earlier this year, even since he was, they first started arresting him, as I described in 2011. And since the Ukraine war has served as a pretext to increasingly ratchet up the punishment for dissent in Russia, I feel like even on that time frame, the repression right now of independent media dissent political opposition in Russia is cranked down tighter than I've ever seen it in the last 25 years, that the repression, in particular, of the media just feels total. And so while the Anti-Corruption Foundation continues during its work, while the opposition continues during its work, while you still try to find ways for people to express their resistance to the Putin regime, looking from the outside, I don't see how you do it, because I don't see that anybody has any space to operate without putting themselves in grave danger. And it just seems like there are so few people who have the kind of superhuman courage and bravery that your husband represented. How do you work in that repressive and environment?",
      "language": "en",
      "emotions": [
        60,
        99,
        76,
        77,
        42,
        75,
        61
      ],
      "emotion": 1
    },
    {
      "segment": 27,
      "start": 507.24284375,
      "end": 567.0478437500001,
      "speaker": 1,
      "path_audio": "segments/27.mp3",
      "path_transcript": "segments/27_transcript.json",
      "transcript": " You are right. There are no independent media inside Russia at all. On newspapers are closed, all even sites and so on, which were independent inside Russia. They are closed. All these editors and all journalists are in exile. And it's very important to remember that there are no at all independent media inside Russia by now. I understand that while we're here in the United States discussing these, it's difficult to believe. Probably two or three of them can work in some ways now. Everybody in exile and a lot of journalists are called foreign engines. Part of our organization is called extremists. Me extremists as well, by the way. There's a rust warrant out there. Yes, there is.",
      "language": "en",
      "emotions": [
        29,
        11,
        50,
        72,
        51,
        22,
        87
      ],
      "emotion": 6
    },
    {
      "segment": 28,
      "start": 565.86659375,
      "end": 566.9465937500001,
      "speaker": 0,
      "path_audio": "segments/28.mp3",
      "path_transcript": "segments/28_transcript.json",
      "transcript": " Yes, they're not sure.",
      "language": "en",
      "emotions": [
        65,
        27,
        88,
        62,
        94,
        97,
        76
      ],
      "emotion": 5
    },
    {
      "segment": 29,
      "start": 567.9253437500001,
      "end": 652.24971875,
      "speaker": 1,
      "path_audio": "segments/29.mp3",
      "path_transcript": "segments/29_transcript.json",
      "transcript": " And it's very difficult to have any communication with people because any connection with me, for example, could be like a criminal case, could be a criminal case, could be open because of this and so on. But still, we are working now in exile. We are based in one of Walter countries and we have Injure, which was in Moscow. We just moved from Moscow and we continue to do everything what we did while we were in Russia. We continue our anti-corruption investigations. We continue our YouTube channels, which are very famous, not just now, these anti-corruption investigations, which we mentioned, but also we have a kind of YouTube TV. So we are doing independent news every day. We are doing a lot of interviews with people who are used to war and Putin's regime. We are doing it every day and we are trying to bring this information and we can see that mostly people in Russia watch our YouTube channels. So they are seeking for these independent information because it's not possible to find anything independent on Russian TV.",
      "language": "en",
      "emotions": [
        5,
        38,
        67,
        59,
        92,
        54,
        69
      ],
      "emotion": 4
    },
    {
      "segment": 30,
      "start": 654.32534375,
      "end": 737.29971875,
      "speaker": 0,
      "path_audio": "segments/30.mp3",
      "path_transcript": "segments/30_transcript.json",
      "transcript": " Alexei writes in the book that when the regime started arresting him and imprisoning him, he says they had two aims. And the first was to hurt his ability to work. He says when you're in prison, it's hard to get your work done. And even when you're under house arrest, it's hard to get your work done. And when he was obviously a very committed candidate for office, I found it very moving that he wrote about not wanting to be a protest or symbolic candidate. He wanted to be a candidate who would win. He believed in democracy and wanted to make people's votes really count for something. So to stop his work, the other reason for arresting him and charging him with the things they charged him with was to undercut his message. He's obviously an anti-corruption crusader, so they would charge him with things that would make him seem like, oh, he's the corrupt one as well. It seems to me though that the other reason that they were, there's a third aim in arresting him and imprisoning him, which is to break down other people's will, to make an example of him so that he, what happened to him would scare other people. Especially after what has happened to him and what has happened to the media and what has happened to the opposition and what has happened with Russia during the Ukraine war, which has made everything worse. Do you still believe that the collapse of the regime is inevitable and that Russia will be democratic one day?",
      "language": "en",
      "emotions": [
        78,
        31,
        82,
        78,
        87,
        68,
        39
      ],
      "emotion": 4
    },
    {
      "segment": 31,
      "start": 738.0759687500001,
      "end": 738.4809687500001,
      "speaker": 1,
      "path_audio": "segments/31.mp3",
      "path_transcript": "segments/31_transcript.json",
      "transcript": "",
      "language": "en",
      "emotions": [
        19,
        12,
        31,
        66,
        12,
        79,
        84
      ],
      "emotion": 6
    },
    {
      "segment": 32,
      "start": 738.4809687500001,
      "end": 738.4978437500001,
      "speaker": 0,
      "path_audio": "segments/32.mp3",
      "path_transcript": "segments/32_transcript.json",
      "transcript": "",
      "language": "en",
      "emotions": [
        22,
        21,
        87,
        50,
        98,
        85,
        78
      ],
      "emotion": 4
    },
    {
      "segment": 33,
      "start": 739.51034375,
      "end": 820.99971875,
      "speaker": 1,
      "path_audio": "segments/33.mp3",
      "path_transcript": "segments/33_transcript.json",
      "transcript": " How could I not believe Alexei's sacrifice all his life for this? And I feel like I must continue his work. I feel like I must continue what he did for many, many years. It's very important for me. And I believe that all these changes, they very often happen in one day. It doesn't mean that we need to sit down and chair and to wait them one day to another day. Of course, we need to do something. But it doesn't mean that we need to expect from people to do everyday huge things. Just to do everything, everyday something small, to encourage people, to motivate people, to show them that we are all together, to get this regime against war, against Putin especially. And we are together in this aim. It's very important. So, absolutely, I believe. And I don't promise you that it happened tomorrow. And we know that it could take years. I absolutely understand it. But for mothers, how to live, if not to believe, in good changes.",
      "language": "en",
      "emotions": [
        51,
        68,
        13,
        28,
        93,
        78,
        61
      ],
      "emotion": 4
    },
    {
      "segment": 34,
      "start": 823.88534375,
      "end": 866.1572187500001,
      "speaker": 0,
      "path_audio": "segments/34.mp3",
      "path_transcript": "segments/34_transcript.json",
      "transcript": " As an American, I feel guilty that my government and my country was not able to do more to stop what they did to your husband. And I feel not necessarily guilty, but frustrated and angry that we haven't been able to do more to stop Putin from doing what he's done to the Russian people and now to the Ukrainian people and beyond. What could America do that we haven't done? What could America do to support effective opposition to his regime? What could America do more? What else could America have done to prevent the murder of your husband?",
      "language": "en",
      "emotions": [
        36,
        97,
        58,
        49,
        1,
        94,
        33
      ],
      "emotion": 1
    },
    {
      "segment": 35,
      "start": 867.2878437500001,
      "end": 961.3490937500001,
      "speaker": 1,
      "path_audio": "segments/35.mp3",
      "path_transcript": "segments/35_transcript.json",
      "transcript": " I don't want to blame anyone for this. Because it's letting her put in who killed my husband, nobody else. But if to take a look at the past, I think that all the governments, democratic governments, will blame this putting for many years the kind of game. Trying to negotiate with him, seeking connections with him, waiting probably that one day he will become one of them, a kind of normal. But the one thing which they didn't notice and which we must remember that putting always life. And I think that government and officials, governments and officials, they just missed this moment. So putting was trying here by year to move these borders and to he was doing awful things more and more awful and everybody was sitting and waiting. Probably the next day he will stop. But we need to remember that he never stopped and of course it was mistake that all this pressure on putting has started just after the war. The war in Ukraine has started.",
      "language": "en",
      "emotions": [
        11,
        1,
        19,
        57,
        27,
        4,
        80
      ],
      "emotion": 6
    },
    {
      "segment": 36,
      "start": 963.86346875,
      "end": 976.33409375,
      "speaker": 0,
      "path_audio": "segments/36.mp3",
      "path_transcript": "segments/36_transcript.json",
      "transcript": " I apologize for asking you an American-centered question, but we have this big, very high-stakes election right now. And I know. You're aware I know. I know. If it.",
      "language": "en",
      "emotions": [
        13,
        59,
        4,
        85,
        11,
        59,
        70
      ],
      "emotion": 3
    },
    {
      "segment": 37,
      "start": 973.51596875,
      "end": 974.56221875,
      "speaker": 1,
      "path_audio": "segments/37.mp3",
      "path_transcript": "segments/37_transcript.json",
      "transcript": " We're behind them.",
      "language": "en",
      "emotions": [
        47,
        32,
        89,
        29,
        14,
        74,
        21
      ],
      "emotion": 2
    },
    {
      "segment": 38,
      "start": 977.19471875,
      "end": 1023.9722187500001,
      "speaker": 0,
      "path_audio": "segments/38.mp3",
      "path_transcript": "segments/38_transcript.json",
      "transcript": " I do think that the relationship, the sort of admiration that the Republican candidate, Donald Trump, has for Putin, is inexplicable. And it's undimmed, hasn't changed at all. I do think that he is proposing that the United States should drop our form of government and adopt something more like what Putin has done to Russia. And if we choose him as our president, that means that America has freely and of our own free will. So, electively chosen that kind of a change for us as a country. And we might do it. I don't know what's going to happen in this election. From your vantage point to you, how does that strike you? What do you think about the fact that America may choose that as its future?",
      "language": "en",
      "emotions": [
        63,
        15,
        4,
        28,
        20,
        86,
        42
      ],
      "emotion": 5
    },
    {
      "segment": 39,
      "start": 1023.9722187500001,
      "end": 1062.02534375,
      "speaker": 1,
      "path_audio": "segments/39.mp3",
      "path_transcript": "segments/39_transcript.json",
      "transcript": " I hope that America will do the right choice. And I believe in democratic institutions, I still think that I know that you have a lot of conversations and they still work or not. But comparing to Russia, I can be just jealous that you are having such things like independent court, independent media. You can criticize candidates on TV. And so I'm sure that America will do the right choice and everything.",
      "language": "en",
      "emotions": [
        61,
        67,
        99,
        22,
        4,
        72,
        94
      ],
      "emotion": 2
    },
    {
      "segment": 40,
      "start": 1062.02534375,
      "end": 1080.9759687500002,
      "speaker": 0,
      "path_audio": "segments/40.mp3",
      "path_transcript": "segments/40_transcript.json",
      "transcript": " you'll be fine. You've had some interaction I know, in particular, with Vice President Kamala Harris, when you were named one of the world's most influential people by Time Magazine, she wrote the write-up about you. What if your interactions with her been like, and do you feel like she understands the stakes of what you're fighting for? Last time I spoke with you.",
      "language": "en",
      "emotions": [
        53,
        70,
        30,
        63,
        44,
        72,
        20
      ],
      "emotion": 5
    },
    {
      "segment": 41,
      "start": 1072.74096875,
      "end": 1120.9022187500002,
      "speaker": 1,
      "path_audio": "segments/41.mp3",
      "path_transcript": "segments/41_transcript.json",
      "transcript": " right up about you. What if your interactions with her been like, and do you feel like she understands the stakes of what you're fighting for? Last time I spoke with her on Thursday, August, by phone. It was, she called me out, Prisoner Swope, which happened between America, Germany, and Russia. And I really appreciate it. It was very warm, very private, and personal talk. And she told me that she remember what my husband and my family did, and are doing to make Russia democratic country. And of course, I very appreciate that exactly at this day she called me, and that means for me a lot.",
      "language": "en",
      "emotions": [
        47,
        47,
        89,
        41,
        24,
        51,
        85
      ],
      "emotion": 2
    },
    {
      "segment": 42,
      "start": 1121.12159375,
      "end": 1165.8740937500002,
      "speaker": 0,
      "path_audio": "segments/42.mp3",
      "path_transcript": "segments/42_transcript.json",
      "transcript": " Last question for you. It means, I think it means a lot to the world that Patriot, a memoir, Alexe's prison diaries, but also his memory, excuse me, but also his memoir are out now. It's a remarkable book. As I said, I did not intend to read all of it. I did not have time. You really messed me up. Sorry. That's OK. But it took a lot to get this out into the world. A lot of risk and a lot of effort. And it is a remarkable document. What do you want people to take away from this? What do you think is the most important thing for people to know about this book?",
      "language": "en",
      "emotions": [
        2,
        54,
        84,
        0,
        23,
        77,
        49
      ],
      "emotion": 2
    },
    {
      "segment": 43,
      "start": 1165.8740937500002,
      "end": 1213.6809687500001,
      "speaker": 1,
      "path_audio": "segments/43.mp3",
      "path_transcript": "segments/43_transcript.json",
      "transcript": " There are two parts. I want people to be encouraged by this book, not to give up, not to continue fight, because as you know, now in the world, there are more and more authoritarian regimes. And Alexey is a great example that people never give up, even in prison, even in torturing conditions. They continue, they are fight, even fight, because he was fighting even from prison. But also, of course, people will know my husband that he was a great man, that he was very kind, very funny, and very beloved person.",
      "language": "en",
      "emotions": [
        58,
        63,
        71,
        96,
        81,
        74,
        17
      ],
      "emotion": 3
    },
    {
      "segment": 44,
      "start": 1213.6809687500001,
      "end": 1214.2884687500002,
      "speaker": 0,
      "path_audio": "segments/44.mp3",
      "path_transcript": "segments/44_transcript.json",
      "transcript": " And",
      "language": "en",
      "emotions": [
        59,
        92,
        1,
        23,
        24,
        43,
        8
      ],
      "emotion": 1
    },
    {
      "segment": 45,
      "start": 1214.2884687500002,
      "end": 1214.64284375,
      "speaker": 1,
      "path_audio": "segments/45.mp3",
      "path_transcript": "segments/45_transcript.json",
      "transcript": "",
      "language": "ko",
      "emotions": [
        94,
        16,
        96,
        86,
        90,
        11,
        97
      ],
      "emotion": 6
    },
    {
      "segment": 46,
      "start": 1214.64284375,
      "end": 1243.9715937500002,
      "speaker": 0,
      "path_audio": "segments/46.mp3",
      "path_transcript": "segments/46_transcript.json",
      "transcript": " sense of humor and his creativity even under duress to me is inspiring. And I don't know other resistance leaders of my generation of my time that bring that to it in a way that really made me think in a completely different way about what it means to stand up for freedom, stand up for for freedom of choice. Yulean the Vanya, it is a real honor to have you here and I wish all the best for you. I just hope doors open for you everywhere and I wish all the best for you. Thank you.",
      "language": "en",
      "emotions": [
        45,
        11,
        93,
        28,
        46,
        99,
        9
      ],
      "emotion": 5
    },
    {
      "segment": 47,
      "start": 1235.70284375,
      "end": 1244.0390937500001,
      "speaker": 1,
      "path_audio": "segments/47.mp3",
      "path_transcript": "segments/47_transcript.json",
      "transcript": " Yulean Navellaniya, it is a real honor to have you here and I wish all the best for you. I just hope doors open for you everywhere and I wish all the best for you. Thank you.",
      "language": "en",
      "emotions": [
        20,
        5,
        4,
        79,
        96,
        67,
        16
      ],
      "emotion": 4
    },
    {
      "segment": 48,
      "start": 1244.0390937500001,
      "end": 1244.96721875,
      "speaker": 0,
      "path_audio": "segments/48.mp3",
      "path_transcript": "segments/48_transcript.json",
      "transcript": " Thank you so much.",
      "language": "en",
      "emotions": [
        13,
        59,
        93,
        33,
        1,
        21,
        1
      ],
      "emotion": 2
    },
    {
      "segment": 49,
      "start": 1244.96721875,
      "end": 1245.3722187500002,
      "speaker": 1,
      "path_audio": "segments/49.mp3",
      "path_transcript": "segments/49_transcript.json",
      "transcript": " on \u03c4\u03bf\u03c5 trustees. Ask Christm kicks me out to talk to Gu Goo And why not please and let us know What you want to think about is before you start the church. Because if we don't",
      "language": "en",
      "emotions": [
        42,
        76,
        52,
        19,
        71,
        62,
        67
      ],
      "emotion": 1
    },
    {
      "segment": 50,
      "start": 1245.3722187500002,
      "end": 1245.7772187500002,
      "speaker": 0,
      "path_audio": "segments/50.mp3",
      "path_transcript": "segments/50_transcript.json",
      "transcript": " Thank you.",
      "language": "en",
      "emotions": [
        8,
        0,
        76,
        53,
        10,
        66,
        49
      ],
      "emotion": 2
    }
  ]
}